config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "snacks#index"

  resources :snacks

  namespace :admin do
    resources :snacks
  end

  namespace :shared do
    namespace :components do
      get 'big_colorful_circle_loader'
    end
  end

end

app/models/snack.rb
class Snack < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    self.admin
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_filter :authenticate_admin!
  
private

  def authenticate_admin!
    authenticate_user!

    raise Pundit::NotAuthorizedError unless current_user.admin?
  end
end

app/controllers/admin/snacks_controller.rb
class Admin::SnacksController < Admin::ApplicationController
  def new
    @snack = Snack.new
  end

  def create
    @snack = Snack.new(snack_params)
    if @snack.save
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
    @snack = Snack.find(params[:id])
  end

  def update
    @snack = Snack.find(params[:id])
    if @snack.update_attributes(snack_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private

  def snack_params
    params.require(:snack).permit(:name, :code, :category, :description, :picture)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def after_sign_in_path_for(resource)
    current_user.admin? ? new_admin_snack_url : root_url
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  before_action :snack_change

  def index
    @snacks = Snack.all
    get_snack_category
    paginate_snacks
  end

  private

  def paginate_snacks
    @snacks = @snacks.paginate(:page => params[:page], :per_page => 20)
  end

  def get_snack_category
    if params[:category]
      @snacks = @snacks.where(category: params[:category])
    end
  end

  def snack_change
    @snack_change = params[:snack_change]
  end

end

app/helpers/admin/snacks_helper.rb
module Admin::SnacksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/snacks_helper.rb
module SnacksHelper
end

app/views/admin/snacks/_form.html.erb
<div class="input-field field">
  <%= f.text_field :name, autofocus: true, class: "validate" %>
  <%= f.label :name %><br />
</div>

<div class="input-field field">
  <%= f.text_field :code, class: "validate" %>
  <%= f.label :code %><br />
</div>

<div class="input-field field">
  <%= f.text_field :category, class: "validate" %>
  <%= f.label :category %><br />
</div>

<div class="input-field field">
  <%= f.text_area :description, class: "validate materialize-textarea" %>
  <%= f.label :description %><br />
</div>

<div class="input-field field">
  <%= f.file_field :picture %>
  <%= f.label :picture %><br />
  <% if f.object.picture? %>
    <%= image_tag f.object.picture.thumb.url %>
    <%= f.check_box :remove_picture %> 
    <%= f.label :remove_picture %>
  <% end %>
</div>

<br/>

app/views/admin/snacks/edit.html.erb
<div class="row padding-top-50">
  <div class="col s6 offset-s3">
    <h3 class="center">Edit Snack</h3>
    <%= form_for @snack, url: { action: "update" } do |f| %>    
      <%= render partial: "form", locals: {snack: @snack, f: f} %>
      <div class="actions center">
        <%= f.submit "Update Snack", class: 'waves-effect waves-light btn-large' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/snacks/new.html.erb
<div class="row padding-top-50">
  <div class="col s6 offset-s3">
    <h3 class="center">New Snack</h3>
    <%= form_for @snack, url: { action: "create" } do |f| %>
      <div class="input-field field">
        <%= f.text_field :name, autofocus: true, class: "validate" %>
        <%= f.label :name %><br />
      </div>

      <div class="input-field field">
        <%= f.text_field :code, class: "validate" %>
        <%= f.label :code %><br />
      </div>

      <div class="input-field field">
        <%= f.text_field :category, class: "validate" %>
        <%= f.label :category %><br />
      </div>

      <div class="input-field field">
        <%= f.text_area :description, class: "validate materialize-textarea" %>
        <%= f.label :description %><br />
      </div>

      <br/>
      <div class="actions center">
        <%= f.submit "Create Snack", class: 'waves-effect waves-light btn-large' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Okashi</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <%=  render 'layouts/components/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/components/_header.html.erb
<ul id='dropdown1' class='dropdown-content'>
  <li><%= link_to 'Profile', edit_user_registration_path %></li>
  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
</ul>

<nav>
  <%= link_to 'Okashi', root_url, class: "brand-logo center" %>

  <ul class="right hide-on-med-and-down">  
    <% if user_signed_in? %>  
      <%= link_to (current_user.email + "<i class='material-icons right'>arrow_drop_down</i>").html_safe, "#!", "data-activates" => "dropdown1", class: "dropdown-button" %>
    <% else %>
      <li><%= link_to 'Log In', new_user_session_path %></li>
      <li><%= link_to 'SIGN UP', new_user_registration_path, class: 'waves-effect waves-light btn' %></li> 
    <% end %>
  </ul>

  <ul id="slide-out" class="side-nav">
    <li><%= link_to 'All Snacks', root_url %></li>
    <li><%= link_to 'Chocolates', snacks_url(category: "chocolates", snack_change: "true") %></li>
    <li><%= link_to 'Biscuits', snacks_url(category: "biscuits", snack_change:"true") %></li>
  </ul>
  
  <div class="row">
    <div class="col s1">
      <%= link_to ("<i class='fa fa-heart-o' aria-hidden='true'></i>").html_safe, "#!", "data-activates" => "slide-out", class:"button-collapse show-on-large category-menu " %>
    </div>
  </div>
</nav>

app/views/shared/components/_big_colorful_circle_loader.html.erb
<div class="preloader-wrapper big active big-colorful-circle-loader">
  <div class="spinner-layer spinner-blue">
    <div class="circle-clipper left">
      <div class="circle"></div>
    </div><div class="gap-patch">
      <div class="circle"></div>
    </div><div class="circle-clipper right">
      <div class="circle"></div>
    </div>
  </div>

  <div class="spinner-layer spinner-red">
    <div class="circle-clipper left">
      <div class="circle"></div>
    </div><div class="gap-patch">
      <div class="circle"></div>
    </div><div class="circle-clipper right">
      <div class="circle"></div>
    </div>
  </div>

  <div class="spinner-layer spinner-yellow">
    <div class="circle-clipper left">
      <div class="circle"></div>
    </div><div class="gap-patch">
      <div class="circle"></div>
    </div><div class="circle-clipper right">
      <div class="circle"></div>
    </div>
  </div>

  <div class="spinner-layer spinner-green">
    <div class="circle-clipper left">
      <div class="circle"></div>
    </div><div class="gap-patch">
      <div class="circle"></div>
    </div><div class="circle-clipper right">
      <div class="circle"></div>
    </div>
  </div>
</div>

app/views/snacks/_snack.html.erb
<div class="snack col s12 m6 l4">  
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <%= image_tag snack.picture.url, class:"activator" %>
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4"><%= snack.name %><i class="material-icons right">more_vert</i></span>
      <p><a href="#">This is a link</a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4"><%= snack.name %><i class="material-icons right">close</i></span>
      <p><%= snack.description %></p>
    </div>
  </div>
</div>

              

app/views/snacks/index.html.erb
<div class="row snacks">
  <%= render partial: "snack", collection: @snacks %>
</div>
<%= will_paginate @snacks %>
<%= render partial: "shared/components/big_colorful_circle_loader" %>

app/views/snacks/index.js.erb
// create new item elements
var $snacks = $('<%= escape_javascript render(partial: "snack", collection: @snacks) %>');
// append items to grid
var $grid = $('.snacks').append( $snacks )
  // add and lay out newly appended items
  .masonry( 'appended', $snacks );

// layout Masonry after each image loads
$grid.imagesLoaded().progress( function() {
  $grid.masonry('layout');
});  

<% if @snacks.next_page %>
  $('.pagination').replaceWith('<%= escape_javascript will_paginate(@snacks) %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
  $('.big-colorful-circle-loader').remove();
<% end %>